#!/bin/bash 

#SBATCH --account=ICT26_ESP_0
#SBATCH --out=./production/LOG_%x_%j.out
#SBATCH --err=./production/LOG_%x_%j.err
#SBATCH --job-name 1d_4gpu_wIO_Nsightprofile
#SBATCH --ntasks-per-node=4
#SBATCH --partition=boost_usr_prod
#SBATCH --nodes=1 
#SBATCH --exclusive 
#SBATCH --gres=tmpfs:100G 
#SBATCH --gres=gpu:4
#SBATCH --time=13:30:00

source /leonardo/home/userexternal/ctica000/MS_thesis/RegCM/modules_cuda  

# Launch
srun ./profile_STD_launch_per_rank.sh 

