#!/bin/bash 

#SBATCH --account=ICT25_ESP_0
#SBATCH --out=./production/interp_offload/LOG_%x_%j.out
#SBATCH --err=./production/interp_offload/LOG_%x_%j.err
#SBATCH --job-name stdpar_8gpu_8task
#SBATCH --ntasks-per-node=4
#SBATCH --partition=boost_usr_prod
#SBATCH --nodes=2
#SBATCH --mem=0G
#SBATCH --gres=tmpfs:100g
#SBATCH --gres=gpu:4
#SBATCH --time=03:00:00

#SBATCH --cpus-per-task=1                              # Number of CPU cores per task. Needed for CPU binding 
#SBATCH --distribution=block:block                     # Distribute tasks in blocks across nodes

#SBATCH --signal=USR1@300                              # Send USR1 signal 5 minutes before time limit is reached  

# Topology-aware placement (keep nodes under a single leaf switch if possible)
##SBATCH --switches=1@7-00:00:00                       # wait up to 7days for compact placement

#SBATCH --nodelist=lrdn[0759-0762,0767-0770,0779-0780] # All in L1 switches: isw30204
source /leonardo/home/userexternal/ctica000/MS_thesis/RegCM/modules_cuda  

# Launch
srun ./STD_launch_per_rank.sh


