#!/bin/bash 

#SBATCH --account=ICT25_ESP_0
#SBATCH --out=./production/LOG_%x_%j.out
#SBATCH --err=./production/LOG_%x_%j.err
#SBATCH --job-name stdpar_64gpu_64task
#SBATCH --ntasks-per-node=4
#SBATCH --partition=boost_usr_prod
#SBATCH --nodes=16
#SBATCH --gres=gpu:4
#SBATCH --time=10:00:00

source /leonardo/home/userexternal/ctica000/MS_thesis/RegCM/modules_cuda  

cd /leonardo/home/userexternal/ctica000/MS_thesis/RegCM/1003_1003_50_1day_Benchmark/parallel_output/Non_MPS_stdpar/64gpu_64proc

# Launch
srun ./STD_launch_per_rank.sh



