#!/bin/bash 

#SBATCH --account=ICT25_MHPC 
#SBATCH --out=./production/LOG_%x_%j.out
#SBATCH --err=./production/LOG_%x_%j.err
#SBATCH --job-name stdpar_800task
#SBATCH --ntasks-per-node=100
#SBATCH --cpus-per-task=1 
#SBATCH --partition=dcgp_usr_prod
#SBATCH --nodes=8
#SBATCH --mem=0G
#SBATCH --gres=tmpfs:100g
#SBATCH --time=02:00:00

source /leonardo/home/userexternal/ctica000/MS_thesis/RegCM/modules_cuda  

# Launch
srun ./STD_launch_per_rank.sh



