#!/bin/bash

#SBATCH --account=ehpc-ben-2026b06-085
#SBATCH --qos=ehpc-ben-2026b06-085
#SBATCH --partition=common
#SBATCH --job-name=discoverer_node_intro_dgx2_7gpu
#SBATCH --nodes=1
#SBATCH --nodelist=dgx2
#SBATCH --ntasks-per-node=7
#SBATCH --cpus-per-task=2
#SBATCH --gres=gpu:7
#SBATCH --exclusive
#SBATCH --time=00:10:00
#SBATCH --output=./introspection/LOG_%x_%j.out
#SBATCH --error=./introspection/LOG_%x_%j.err

set -euo pipefail

cd "$SLURM_SUBMIT_DIR"
mkdir -p introspection

REGCM_ROOT=/valhalla/projects/ehpc-ben-2026b06-085/tchristian/work/RegCM
source "$REGCM_ROOT/environment_loader/regcm5_discoverer_nvhpc25_1_hpcx_cuda12.sh"

source ./discoverer_node_introspection_mem_unified_probe.job
