#!/bin/bash 

#SBATCH --account=ICT26_ESP_0
#SBATCH --out=./production/LOG_%x_%j.out
#SBATCH --err=./production/LOG_%x_%j.err
#SBATCH --job-name 7d_16g_no_IO_profile
#SBATCH --ntasks-per-node=4
#SBATCH --partition=boost_usr_prod
#SBATCH --nodes=4
#SBATCH --exclusive
#SBATCH --gres=tmpfs:100g
#SBATCH --gres=gpu:4
#SBATCH --time=01:00:00

source /leonardo/home/userexternal/ctica000/MS_thesis/RegCM/modules_cuda  

# Launch
srun ./STD_launch_per_rank.sh


