#!/bin/bash 

#SBATCH --account=ehpc575
#SBATCH --out=./production/LOG_%x_%j.out
#SBATCH --err=./production/LOG_%x_%j.err
#SBATCH --job-name stdpar_16gpu_16task
#SBATCH --ntasks-per-node=4
#SBATCH --partition=acc
#SBATCH --qos=acc_ehpc
#SBATCH --nodes=4
#SBATCH --exclusive
#SBATCH --gres=tmpfs:100g
#SBATCH --gres=gpu:4
#SBATCH --time=00:30:00

# export BINDIR=/home/ictp/ictp992004/latest_managed
export BINDIR=/home/ictp/ictp549985/RegCM/bin

source /gpfs/home/ictp/ictp549985/RegCM/modules_cuda_working_old  
# source /home/ictp/ictp992004/module


export OMPI_MCA_pml=ucx
export OMPI_MCA_btl=^openib,smcuda

# 2) UCX transports – include CUDA + GDRCopy paths
export UCX_TLS=cma,rc,mm,cuda_copy,cuda_ipc,gdr_cop


# UCX tuning (start minimal)
export UCX_RNDV_FRAG_MEM_TYPE=cuda
export UCX_RNDV_FRAG_SIZE=cuda:32M
export UCX_RNDV_THRESH=128

export UCX_TLS=cma,rc,mm,cuda_copy,cuda_ipc,gdr_copy
# Launch
mpirun -np 16 --bind-to none --mca pml ucx $BINDIR/regcmMPICLM45 EURR-3_namelist.in   
# mpirun -np 16 ./STD_launch_per_rank.sh  

