#!/bin/bash 

#SBATCH --account=ICT25_MHPC_0
#SBATCH --out=./production/std/LOG_%x_%j.out
#SBATCH --err=./production/std/LOG_%x_%j.err
#SBATCH --job-name Std_Par
#SBATCH --ntasks-per-node=4
#SBATCH --partition=boost_usr_prod
#SBATCH --nodes=2
#SBATCH --gres=gpu:4
#SBATCH --mem=123000
#SBATCH --time=02:00:00

source /leonardo/home/userexternal/ctica000/MS_thesis/RegCM/modules_cuda  


cd /leonardo/home/userexternal/ctica000/MS_thesis/RegCM/run

# Launch
srun ./STD_launch_per_rank.sh



