#!/bin/bash

#SBATCH --account=ICT25_MHPC_0
#SBATCH --qos=boost_qos_dbg
#SBATCH --out=./output/LOG_%x_%j.out
#SBATCH --err=./output/LOG_%x_%j.err
#SBATCH --job-name Std_Par
#SBATCH --ntasks-per-node=4
#SBATCH --partition=boost_usr_prod
#SBATCH --nodes=2
#SBATCH --gres=gpu:4
#SBATCH --mem=123000

source /leonardo/home/userexternal/ctica000/MS_thesis/RegCM/modules_cuda

cd /leonardo/home/userexternal/ctica000/MS_thesis/RegCM/run

export BINDIR=/leonardo/home/userexternal/ctica000/MS_thesis/RegCM/bin

srun $BINDIR/regcmMPIOPENACC_STDPAR_RCEMIP isc24_small.in
